@startuml SequenceDiagram
actor User
participant "REST-capable Client"
participant "REST-auto-exposed Repository"
collections Entities
database Database
User -> "REST-capable Client" : uses
"REST-capable Client" -> "REST-auto-exposed Repository" : remotely calls
"REST-auto-exposed Repository" -> Entities : manages
Entities <--> Database : mapped to
"REST-auto-exposed Repository" --> "REST-capable Client" : remotely returns
"REST-capable Client" --> User : serves
@enduml