@startuml EntityClassDiagram
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Product
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Customer
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Brand
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Category
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Order
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.OrderLine
ma.aui.sse.it.xcommerce.monolithic.data.entities.AbstractEntity <|-- ma.aui.sse.it.xcommerce.monolithic.data.entities.Review
ma.aui.sse.it.xcommerce.monolithic.data.entities.Brand "1" *-- "many" ma.aui.sse.it.xcommerce.monolithic.data.entities.Product : has
ma.aui.sse.it.xcommerce.monolithic.data.entities.Product "1" *-- "many" ma.aui.sse.it.xcommerce.monolithic.data.entities.Review : has
ma.aui.sse.it.xcommerce.monolithic.data.entities.Category "1" *-- "many" ma.aui.sse.it.xcommerce.monolithic.data.entities.Product : has
ma.aui.sse.it.xcommerce.monolithic.data.entities.Category "1" o-- "many" ma.aui.sse.it.xcommerce.monolithic.data.entities.Category : has
ma.aui.sse.it.xcommerce.monolithic.data.entities.Order "1" *-- "many" ma.aui.sse.it.xcommerce.monolithic.data.entities.OrderLine : has
@enduml

@startuml RepositoriesServicesClassDiagram
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.ProductRepository
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.BrandRepository
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.CategoryRepository
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.CustomerRepository
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.OrderRepository
org.springframework.data.repository.CrudRepository <|-- ma.aui.sse.it.xcommerce.monolithic.data.repositories.ReviewRepository
ma.aui.sse.it.xcommerce.monolithic.services.ShoppingCartService "1" *-- "1" ma.aui.sse.it.xcommerce.monolithic.data.repositories.ProductRepository : uses
ma.aui.sse.it.xcommerce.monolithic.services.OrderService "1" *-- "1" ma.aui.sse.it.xcommerce.monolithic.services.ShoppingCartService : uses
ma.aui.sse.it.xcommerce.monolithic.services.OrderService "1" *-- "1" ma.aui.sse.it.xcommerce.monolithic.data.repositories.CustomerRepository : uses
ma.aui.sse.it.xcommerce.monolithic.services.OrderService "1" *-- "1" ma.aui.sse.it.xcommerce.monolithic.data.repositories.OrderRepository : uses
@enduml