@startuml SequenceDiagram
actor User as User
participant "Rich UI\nREST-capable\nClient" as Client
participant "REST-auto-exposed\nRepository" as Repository
collections Entities as Ent
database Database as DB
User -> Client : uses
Client -> Repository : remotely calls
Repository -> Ent : manages
Ent <--> DB : mapped to
Repository --> Client : remotely returns
Client --> User : serves
@enduml