@startuml SequenceDiagram
actor User as U
participant "REST-uncapable\nWeb Client" as RUC
participant "Web\nFront-end" as WFE
participant "REST-auto-exposed\nRepository" as R
collections Entities as E
database Database as DB
U -> RUC : uses
RUC -> WFE : HTTP request
WFE -> R : remotely calls
R -> E : manages
E <--> DB : mapped to
R --> WFE : remotely returns
WFE --> RUC : HTTP reply
RUC --> U : serves
@enduml